"""ChainTrace Graph Visualization Component Slot.

Provides a dedicated wrapper tab/slot for Person D to plug in Pyvis-rendered HTML graph output
embedded via streamlit.components.v1.html without modifying dashboard core logic.
"""

from __future__ import annotations

import os
import streamlit as st
import streamlit.components.v1 as components


def render_graph_section(
    selected_entity: str | None = None, html_path: str = "outputs/graphs/cluster_graph.html"
) -> None:
    """Render interactive Pyvis network graph section.

    Args:
        selected_entity: Entity ID currently focused by user in alert table.
        html_path: Path to Pyvis exported HTML file generated by visualization module.
    """
    st.markdown("### 🕸️ Entity-Transaction Network Graph Analysis")

    if selected_entity:
        st.info(f"🎯 Currently Focusing Graph Node: `{selected_entity}`")
    else:
        st.caption("Select an entity from the Alert Table above or click nodes below to inspect link analysis.")

    # Check if a custom pyvis graph HTML file exists on disk
    if os.path.exists(html_path):
        try:
            with open(html_path, "r", encoding="utf-8") as f:
                html_content = f.read()

            components.html(html_content, height=600, scrolling=True)
            return
        except Exception as e:
            st.warning(f"Could not load local graph HTML file ({e}). Displaying default interactive graph slot.")

    # Fallback default interactive Pyvis graph generator for demo
    try:
        from pyvis.network import Network

        net = Network(height="550px", width="100%", bgcolor="#0b0e14", font_color="#f0f4f8", directed=True)
        net.barcode = False

        # Add sample cluster nodes matching demo theme
        nodes = [
            ("bc1q9x74a0v9g8z", "Wallet (Target)", "#ff1744", 25, "Illcit Seed Wallet\nScore: 0.945"),
            ("tx_8812a4f0", "Transaction", "#00e5ff", 18, "TX: tx_8812a4f0\nFee: 0.0005 BTC"),
            ("3J98t1WpEZ73CN", "Wallet", "#ff9100", 20, "Intermediary Wallet\nScore: 0.780"),
            ("1A1zP1eP5QGefi", "Wallet", "#00e676", 15, "Licit Counterparty\nScore: 0.120"),
            ("185.220.101.45", "IP Endpoint", "#7c4dff", 15, "TOR Relay IP (Romania)"),
            ("AS60068 Datacamp", "ASN Node", "#3d5afe", 15, "AS60068 Datacamp"),
        ]

        for nid, ntype, color, size, title in nodes:
            is_focus = selected_entity and (selected_entity in nid or nid in selected_entity)
            border_color = "#ffffff" if is_focus else color
            border_width = 4 if is_focus else 1

            net.add_node(
                nid,
                label=nid[:12] + "..." if len(nid) > 12 else nid,
                title=title,
                color={"background": color, "border": border_color},
                borderWidth=border_width,
                size=size + (8 if is_focus else 0),
            )

        edges = [
            ("bc1q9x74a0v9g8z", "tx_8812a4f0", "4.52 BTC"),
            ("tx_8812a4f0", "3J98t1WpEZ73CN", "4.50 BTC"),
            ("tx_8812a4f0", "1A1zP1eP5QGefi", "0.02 BTC"),
            ("185.220.101.45", "tx_8812a4f0", "P2P Relay"),
            ("185.220.101.45", "AS60068 Datacamp", "Hosted"),
        ]

        for src, dst, label in edges:
            net.add_edge(src, dst, title=label, color="#232f48", width=2)

        # Generate HTML content string directly
        html_code = net.generate_html()
        components.html(html_code, height=580, scrolling=False)

    except Exception as err:
        st.markdown(
            f"""
            <div style="background: #121824; border: 1px dashed #232f48; border-radius: 8px; padding: 2rem; text-align: center;">
                <h4 style="color: #00e5ff; margin-bottom: 0.5rem;">🕸️ Pyvis Graph Visualization Slot Ready</h4>
                <p style="color: #94a3b8; font-size: 0.9rem;">
                    Teammate (Person D) can embed Pyvis HTML outputs directly here using <code>components.html()</code>.
                </p>
                <code style="color: #ff9100;">streamlit.components.v1.html(open('{html_path}').read(), height=600)</code>
            </div>
            """,
            unsafe_allow_html=True,
        )
